perfectcushion/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = 'index'),
    path('shop/', include('shop.urls')),
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views

app_name='shop'

urlpatterns = [
   path('',views.allProdCat, name ='allProdCat'),
   path('<slug:c_slug>/',views.allProdCat,name='products_by_category'),
   path('<slug:c_slug>/<slug:product_slug>/', views.ProdCatDetail,name='ProdCatDetail'),
   ]

shop/models.py
from django.db import models
from django.urls import reverse
 
class Category(models.Model):
  name = models.CharField(max_length=250, unique=True)
  slug = models.SlugField(max_length=250, unique=True)
  description = models.TextField(blank=True)
  image = models.ImageField(upload_to='category', blank=True)
 
  class Meta:
    ordering = ('name',)
    verbose_name = 'category'
    verbose_name_plural = 'categories'
 
  def get_url(self):
    return reverse('shop:products_by_category', args=[self.slug])
 
  def __str__(self):
    return '{}'.format(self.name)
 
class Product(models.Model):
  name = models.CharField(max_length=250, unique=True)
  slug = models.SlugField(max_length=250, unique=True)
  description = models.TextField(blank=True)
  category = models.ForeignKey(Category, on_delete=models.CASCADE)
  price = models.DecimalField(max_digits=10, decimal_places=2)
  image = models.ImageField(upload_to='product', blank=True)
  stock = models.IntegerField()
  available = models.BooleanField(default=True)
  created = models.DateTimeField(auto_now_add=True)
  updated = models.DateTimeField(auto_now=True)
 
  class Meta:
    ordering = ('name',)
    verbose_name = 'product'
    verbose_name_plural = 'products'
 
  def get_url(self):
    return reverse('shop:ProdCatDetail', args=[self.category.slug, self.slug])
 
  def __str__(self):
    return '{}'.format(self.name)

shop/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from.models import Category,Product

def index(request):
	test_var = 'This is my first app web page'
	return HttpResponse(test_var)

#Category view

def allProdCat(request, c_slug=None):
	c_page = None
	products = None
	if c_slug!=None:
		c_page = get_object_or_404(Category,slug=c_slug)
		products = Product.objects.filter(category=c_page,available=True)
	else:
		products = Product.objects.all().filter(available=True)
	return render(request,'shop/category.html',{'category':c_page,'products':products})

def ProdCatDetail(request, c_slug, product_slug):
	try:
		product = Product.objects.get(category__slug=c_slug,slug=product_slug)
	except Exception as e:
		raise e
	return render(request,'shop/product.html', {'product': product})

shop/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lan="en">
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name ="description" content="{% block metadescription %} {% endblock %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
	<link rel="stylesheet" href="{% static 'css/custom.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<title>{% block title %} {% endblock %}</title>
</head>
<body>
	<div class="container">
		{% include 'header.html' %}
		{% include 'navbar.html' %}
		{% block content %}
		{% endblock %}
	</div>
	    {% include 'footer.html' %}
	    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}" ></script>
</body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my_footer">
  <p class ="text-center">&copy; Udemy Training.  All Rights Reserved.</p>
</div>

shop/templates/header.html
{% load staticfiles %}
<header>
	<center>
		<a href="{% url 'shop:allProdCat' %}"><img src="{% static 'img/logo.png' %}" alt = "Perfect Cushion Store">
	</center>
</header>

shop/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      

        <a class="nav-link text-uppercase" href="#">Home <span class="sr-only">(current)</span></a>
      
      <li class="nav-item dropdown {% if 'shop' in request.path %}active{% endif %}">
        <a class="nav-link dropdown-toggle text-uppercase" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Shop
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item text-uppercase" href="{% url 'shop:allProdCat' %}">All Products</a>
          {% for cat in links %}
          <a class="dropdown-item text-uppercase" href="{{cat.get_url}}">{{cat.name}}</a>
          {% endfor %}
        </div>
</li>
      <li class="nav-item">
        <a class="nav-link" href="#">Your Cart()</a>
      </li>
      
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

shop/templates/shop/category.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
  {% if category %}
    {{ category.description|truncatewords:155 }}
  {% else %}
     Welcome to the cushion store where you can buy comfy and awesome cushions
  {% endif %}
{% endblock %}
{% block title %}
  {% if category %}
    {{ category.name}} - Perfect Cushion Store
  {% else %}
     See Our Cushion Collection - Perfect Cushions
  {% endif %}
{% endblock %}
{% block content %}
  {% if category %}
    <div class="row my_row_class">
    	<div class="mx-auto">
    		<p><a href="{% url 'shop:allProdCat' %}">Our Product Collection</a> | {{ category.name }}</p>
    	</div>
    </div>
    {% endif %}
    <div class="mx-auto">
    {% if category %}
        <img class="my_image" src="{{category.image.url}}" alt="{{category.name}}">
    </div>
    <br>
    <div>
    	<h1 class="text-center my_title">{{category.name}}</h1>
    	<p class="text-justify">{{category.description}}</p>
    </div>
    {% else %}
      <img src="{% static 'img/banner.jpg' %}" alt="Our Products Collection">
     </div>
     <br>
     <div>
     	<h1>Our Products Collection</h1>
     	<p>Finding the perfect cushion for your room can instantly add to the levels of comfort and sense of style throughout your home.  They can transform the blandest of decors instantly by adding colour, softness and an air of coziness.  As well as being comfy and looking great our range of cushions will certainly embolden your decor with personalized charm</p>
     </div>
     {% endif %}
     <div>
     	<div>
     		{% for product in products %}
     		  <div>
     		  	<div>
     		  		<a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="{{product.name}}"></a>
     		  		  <div>
     		  		  	<h4>{{product.name}}</h4>
     		  		  	<p>${{product.price}}</p>
     		  		  </div>
     		  	</div>
     	</div>
     	     {% endfor %}
     </div>
  </div>
    
 {% endblock %}

shop/templates/shop/product.html
{% extends "base.html" %}
{% load staticfiles %}
{% block metadescription %}
   {{ product.description|truncatewords:155 }}
{% endblock %}
{% block title %}
    {{ product.name }} - Perfect Cushion Store
 {% endblock %}
 {% block content %}
     <div>
     	<div>
     		<p><a href="{% url 'shop:allProdCat' %}"></a> | <a href="{{ product.category.get_url }}">{{product.category}}</a> | {{product.name }}</p>
     	</div>
     	<div>
     		<br>
     		<div>
     			<div>
     				<div>
     					<img src="{{product.image.url}}" alt = "{{product.name}}">
     				</div>
     			</div>
     			<div>
     				<h1>{{product.name}}</h1>
                    <p>${{product.price}}</p>
                    <p>Product Description</p>
                    <p>{{product.description}}</p>
                    {% if product.stock <= 0 %}
                      <p><b>Out of Stock</b></p>
                    {% else %}
                       <a href="">Add to Cart</a>
                    {% endif %}
                 </div>
               </div>
             </div>
           </div>
     </div>
  {% endblock %}